### PR TITLE
Fixes script race condition, updates react to latest and fixes travis tests

### LINKED ISSUE #49: Update react to v0.14
please see [this](https://www.npmjs.com/package/react-bootstrap#react-v0-13-support)

### LINKED ISSUE #59: V8Js::executeString():1: TypeError: Cannot call method 'renderToString' of undefined
I am getting this error while using this package..

### PR DESCRIPTION
**Pull request by TomCaserta**
- Fixes #59 
- Fixes #49
- Fixes #58 
- Fixes #57 

Hopefully this fixes everything! We can bundle the react js source files together if required, should make it more user friendly, although having just checked it seems like the react-php-v8js already creates a bundle file we can use. In any case that can be implemented later, this will just fix it for now.

### CODE REVIEW

**Comment by talyssonoc** [comment]
Nice!!! Gonna merge it, it really seems to fix a lot of previous bugs. Thanks for your contribution :smile:

File: assets/react_ujs.js [hunk 1]
```diff
@@ -40,12 +40,17 @@
...
 
       for(var i = 0; i < elements.length; i++) {
-        React.unmountComponentAtNode(elements[i]);
+        ReactDOM.unmountComponentAtNode(elements[i]);
       }
     },
 
     handleEvents: function handleEvents() {
-      document.addEventListener('DOMContentLoaded', ReactLaravelUJS.mountComponents);
+      if (document.readyState == "complete" || document.readyState == "loaded" || document.readyState == "interactive") {
```
Comment (TomCaserta) [inline assets/react_ujs.js:48]: The line I was referencing in issue #68. Perhaps this may need to be modified.
